name: "Standalone"

on: [push]

jobs:
  execute:
    name: "Supported OS / Build, Test and Run"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operative-system: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
        environments: [Debug, Release]
    steps:
      - uses: actions/checkout@v3
      -
        name: Dependencies
        run: |
          sudo apt update 
          sudo apt install build-essential
          sudo wget -q https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.gz
          sudo tar -xf boost_1_79_0.tar.gz
          cd boost_1_79_0
          sudo ./bootstrap.sh
          sudo ./b2
          
          ls -l
