name: "Container"

on: [push]

jobs:
  compile-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: [Debug, Release]
    env:
      CORE_MODE: ${{ matrix.environments }}
    name: "Supported Architectures / Compile And Push"
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: "zencommunity/core:${{ github.ref_name }}-${{ matrix.environments }}"
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v6,linux/arm/7
          file: Dockerfile
          no-cache: true
      -
        name: Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  execute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: [Debug, Release]
    name: "Supported Architectures / Run / ${{ matrix.environments }}"
    env:
      CORE_MODE: ${{ matrix.environments }}
    container: "zencommunity/core:${{ github.ref_name }}-${{ matrix.environments }}"
    needs: [compile-and-push]
    steps:
      -
        name: Run
        run: cd /app && ./Core
      -
        name: Digest
        run: echo "${{ github.sha }}"