name: "Container"

on: [push]

jobs:
  compile-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: [Debug, Release]
    env:
      APP_ENV: ${{ matrix.environments }}
    name: "Supported Architectures / Compile And Push"
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: "zencommunity/core:${{ github.ref_name }}-${{ matrix.environments }}"
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          no-cache: true
      -
        name: Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  execute:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: [Debug, Release]
    name: "Supported Architectures / Run / ${{ matrix.environments }}"
    env:
      APP_ENV: ${{ matrix.environments }}
    container: "zencommunity/core:${{ github.ref_name }}-${{ matrix.environments }}"
    needs: [compile-and-push]
    steps:
      -
        name: Run
        run: cd /app && ./Test
      - name: Zip Binary
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ github.ref_name }}-${{ matrix.environments }}.zip /app/Core
      - name: Upload Binary
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_API_TOKEN }}
          file: ${{ github.ref_name }}-${{ matrix.environments }}.zip
          asset_name: "${{ github.ref_name }}—${{ matrix.environments }}.zip"
          tag: ${{ github.ref }}
          overwrite: true