name: "Docker"

on: [push]

jobs:
  compile-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: [Debug, Release]
    env:
      CORE_MODE: ${{ matrix.environments }}
    name: "Compile And Push on ${{ matrix.environments }}"
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "zencommunity/core:${{ matrix.environments }}-${{ github.sha }}"
          context: .
          file: Dockerfile
          no-cache: true
      -
        name: Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  execute:
    name: "Run"
    runs-on: ubuntu-latest
    container: "zencommunity/core:${{ matrix.environments }}-${{ github.sha }}"
    needs: [compile-and-push]
    steps:
      -
        name: Run
        run: cd /app && ./Core
      -
        name: Digest
        run: echo "${{ github.sha }}"